#!/usr/bin/env ruby
# frozen_string_literal: true

require "bibtex"
require "fileutils"
require "yaml"

ROOT = File.expand_path("..", __dir__)
BIB_PATH = File.join(ROOT, "_bibliography", "publications.bib")
SOURCE_PATH = File.join(ROOT, "_data", "publications.yml")
OUTPUT_PATH = File.join(ROOT, "_data", "publications_resolved.yml")

def field(entry, *names)
  names.each do |name|
    value = entry[name]
    next if value.nil?

    value = value.to_s.strip.gsub(/\u2018|\u2019/, "'")
    return value unless value.empty?
  end

  nil
end

def compact_hash(hash)
  hash.reject do |_, value|
    value.nil? || (value.respond_to?(:empty?) && value.empty?)
  end
end

def author_names(entry)
  names = entry.author
  return [] if names.nil?

  names.map { |name| name.display_order.to_s.strip }.reject(&:empty?)
end

def venue(entry)
  main = field(entry, :booktitle, :journal, :conference, :publisher, :school, :institution)
  series = field(entry, :series)

  return series if main.nil?
  return main if series.nil? || main.include?(series)

  "#{main} (#{series})"
end

def year(entry)
  value = field(entry, :year)
  return nil if value.nil?

  value.match?(/\A\d+\z/) ? value.to_i : value
end

def doi(entry)
  value = field(entry, :doi)
  value&.gsub(/\s+/, "")
end

def url(entry, doi_value)
  field(entry, :url, :link) || (doi_value && "https://doi.org/#{doi_value}")
end

def bib_record(entry)
  doi_value = doi(entry)
  authors = author_names(entry)

  compact_hash(
    {
      "key" => entry.key,
      "entry_type" => entry.type.to_s,
      "title" => field(entry, :title),
      "authors" => authors,
      "venue" => venue(entry),
      "year" => year(entry),
      "doi" => doi_value,
      "url" => url(entry, doi_value),
      "abstract" => field(entry, :abstract)
    }
  )
end

unless File.exist?(BIB_PATH)
  abort "Missing BibTeX file: #{BIB_PATH}"
end

unless File.exist?(SOURCE_PATH)
  abort "Missing publication source file: #{SOURCE_PATH}"
end

source = YAML.safe_load_file(SOURCE_PATH, aliases: true) || []
unless source.is_a?(Array)
  abort "#{SOURCE_PATH} must contain a YAML list of publications"
end

bibliography = BibTeX.open(BIB_PATH, filter: :latex)

resolved = source.each_with_index.map do |publication, index|
  unless publication.is_a?(Hash)
    abort "Publication #{index + 1} in #{SOURCE_PATH} must be a YAML object"
  end

  publication = compact_hash(publication.transform_keys(&:to_s))
  key = publication["key"]

  next publication if key.nil? || key.empty?

  entry = bibliography.entries[key]
  abort "No BibTeX entry found for key #{key.inspect} in #{BIB_PATH}" if entry.nil?

  bib_record(entry).merge(publication)
end

FileUtils.mkdir_p(File.dirname(OUTPUT_PATH))
File.write(
  OUTPUT_PATH,
  "# Generated by scripts/build_publications.rb from _bibliography/publications.bib and _data/publications.yml.\n" \
  "# Edit those source files instead of this one.\n" \
  "#{resolved.to_yaml}"
)

puts "Wrote #{OUTPUT_PATH.delete_prefix("#{ROOT}/")}"
